### ISSUE TITLE
Unable to run the tool on Kali linux

### ISSUE THREAD

**Issue by edwinsunder** [LeeXiaolan/hwfw-tool#5]
The below errors occur
1. Does anyone have a compiled binary executable for hwfw?
2. Tested with more than one BIN file - anyway the errors are talking about the script having an issue.
3. Just FYI - I have a HG8145v device that I am trying to unlock - It lets me go to shell but i cant do anything there except for exit or run one .sh file
4. Main question once unpacked and then modified - will I be able to burn this Modified/edited firmware from the routers webpage - where it lets you select and upgrade firmware's from?
5. Or will it need the HW_ONT_Tool.exe to burn/write the firmware to router?

─# python hwfw.py unpack -v -r fw/ ./test2/R020.bin
Traceback (most recent call last):
  File "/home/kali/Downloads/hwfw/hwfw.py", line 287, in <module>
    main()
  File "/home/kali/Downloads/hwfw/hwfw.py", line 284, in main
    sys.exit(entry(opt))
             ^^^^^^^^^^
  File "/home/kali/Downloads/hwfw/hwfw.py", line 268, in entry
    return unpack(opt)
           ^^^^^^^^^^^
  File "/home/kali/Downloads/hwfw/hwfw.py", line 259, in unpack
    fw.open(opt['FILE'])
  File "/home/kali/Downloads/hwfw/hwfw.py", line 47, in open
    self._loadFromString(data, noItemData)
  File "/home/kali/Downloads/hwfw/hwfw.py", line 55, in _loadFromString
    offset += self._parseItemInfo(data, offset, noItemData)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Downloads/hwfw/hwfw.py", line 71, in _parseItemInfo
    for i in xrange(self.header.itemCount):
             ^^^^^^
NameError: name 'xrange' is not defined. Did you mean: 'range'?

**Comment by D0MlNIC** [comment]
I don't know if you are still trying to achieve the above task.

But this python script is written in python2 not in python3.
